### ISSUE TITLE
library "libbluetooth_jni.so" not found

### ISSUE THREAD

**Issue by seasonyuu** [kavishdevar/aln#16]
**Describe the bug**
Using on Android 14 (Lineage OS 21.0), Pixel 3 device.
After place `bt.sh` into `/data/adb/post-fs-data.d/` and reboot device.

```
FATAL EXCEPTION: main
	Process: com.android.bluetooth, PID: 4186
	java.lang.UnsatisfiedLinkError: dlopen failed: library "libbluetooth_jni.so" not found
		at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
		at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
		at java.lang.System.loadLibrary(System.java:1765)
		at com.android.bluetooth.btservice.AdapterService.<clinit>(AdapterService.java:195)
		at java.lang.Class.newInstance(Native Method)
		at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
		at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:74)
		at android.app.ActivityThread.handleCreateService(ActivityThread.java:4884)
		at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
		at android.os.Handler.dispatchMessage(Handler.java:107)
		at android.os.Looper.loopOnce(Looper.java:232)
		at android.os.Looper.loop(Looper.java:317)
		at android.app.ActivityThread.main(ActivityThread.java:8592)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**To Reproduce**
1. place `libbluetooth_jni.so` to those two "overlay" file
2. place `bt.sh` to `/data/adb/post-fs-data.d/`
3. created the magisk module stuff
4. reboot device

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/eafb86fd-1081-4754-ba72-cf3dc196ad37)

<img width="562" alt="image" src="https://github.com/user-attachments/assets/56b6b61a-e611-404d-927f-b8b680afb828" />

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/1908592d-da5a-4790-a2a1-abcd840f4fc9" />

**Desktop (please complete the following information):**
 - Distro: [e.g. Ubuntu, KDE Neon, Arch]
 - Version [e.g. 22.04]

**Additional context**

**Comment by seasonyuu** [comment]
More infos:
<img width="627" alt="image" src="https://github.com/user-attachments/assets/5c674cd2-5d20-48d1-853e-586c5fb5a356" />

**Comment by kavishdevar** [comment]
Hi, thanks for trying out the project!

Could you please disable all the modifications you made for the workaround and send me the output of `lsof | grep libbluetooth`?

To disable the modifications-
1. You can disable the module from the root manager app itself.
2. And, for the `bt.sh` you could comment the lines in there.

Thanks!

**Comment by seasonyuu** [comment]
> Hi, thanks for trying out the project!
> 
> Could you please disable all the modifications you made for the workaround and send me the output of `lsof | grep libbluetooth`?
> 
> To disable the modifications-
> 
> 1. You can disable the module from the root manager app itself.
> 2. And, for the `bt.sh` you could comment the lines in there.
> 
> Thanks!

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/8b55e1c8-d541-4d00-8cb6-d794c90d1c46" />

**Comment by kavishdevar** [comment]
Seems like the folder structure is the same and shouldn't cause problems. Can you follow the steps again, and make sure that the root module has been created and enabled correctly? Your screenshots and logs show that most likely that the root module was not created/enabled or doesn't work.

**Comment by kavishdevar** [comment]
Please follow the instructions in [the README](https://github.com/kavishdevar/aln#installation) for a simplified installation process. You need to install a module available in the [latest nightly release](https://github.com/kavishdevar/aln/releases/).

Closing as obselete. Please create a new issue if needed.
